language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: Vrfdu0I17u92pVMHxRZyxGX/V21RauGODffKgCR0Y3gEVVTOW7EHXkiJ7bpX0ivs6Vzwc3mRkimAIKspW3+/wvk2coUtSXqgh9vq24O+025GUvVGtSBa2G9P9V3J/NxDTwHBFdli+T9TNMD3EsA6q8ZTi1tX2JDdoSb7zQz7fe1pmYyxn+oxSj6nrSm9xPwWBLgnWcIakkfrDbQynjWlxpgNXY3RcmgY22hkDpXKZkJT/8wKbxPMfHifco4tJrjYljvGtQdJpeTrv379dgN7In6CGticU4pYKYt9sfzKz4EvBFcmnkUxF8sjYgBr08jxS+ye+wu1oOtBiOq6aBEjS4A8jSmA6ZX0bdyFcWwbL5lD88DZaUb5XLiRkjjjEyP+RbRDV+uO4X1CdR/6fmcWv8Bn77xcSUbzJE3xSu4DxQ9Ph8dNuQeyx/kfgdq9F0Rni/ij3uf5Wz0WudPwLC7eALTcQ2IcyJgxuzSBFMkhdNTcvTcPuAWJSO2n6gsF3K3RFfptYfVo8JhmZaCvnr/cccAsBNa7Xj/X1fcPDNzkrGqL2CeKkDVQXYYB5tyTvKJrcxE/H4HDk3IsOL4nKV1XiwRHZAJJ+2gkvb0trWRYL1oe7HRPL5kRh3JlHpay3WQmiFqb3fvr+0tv1PzsJRnvpSHtUCoa/GF8h0BOPARpHwI=
  app: hotorcold
  on:
    repo: Mrjustinfry/hotorcold
